export const questions = [
  "Ich möchte eine Haftung mit meinem Privatvermögen ausschließen",
  "Die Gesellschaft soll mit geringem Aufwand und niedrigen Kosten gegründet werden ",
  "Die regelmäßige Verwaltung der Gesellschaft soll nur geringen Aufwand bzw. Kosten verursachen",
  "Die Gesellschaft muss für große Familiengesellschaften mit vielen Gesellschaftern und divergierenden Interessen geeignet sein",
  "Minderjährige Kinder sollen am Unternehmen teilhaben ",
  "Meine Ideen und Vorstellungen für das Unternehmen sollen für lange Zeiträume unveränderlich festgeschrieben sein",
  "Die Satzung und Organisationstruktur der Gesellschaft soll flexibel nach meinen Vorstellungen gestaltbar sein ",
  "Einzelnen Gesellschaftern sollen Sonderrechte eingeräumt werden ",
  "Ich möchte die Geschicke der Gesellschaft kontrollieren können, obwohl keine Beteiligungsmehrheit (mehr)  besteht",
  "Die Gesellschaft soll eine familienfremde Geschäftsführung haben (können)",
  "Ich möchte das operative Geschäft der Gesellschaft als Gesellschafter unmittelbar beeinflussen können",
  "Die Organisation und Struktur der Geschäftsführung soll maßgeschneidert und flexibel gestaltet werden können",
  "Die Unternehmensführung soll möglichst unabhängig von der Unternehmerfamilie agieren können",
  "Die Gesellschafter können einen Beirat nach ihren Vorstellungen installieren",
  "Eine vorteilhafte Besteuerung für thesaurierte Gewinne ist wichtig ",
  "Eine vorteilhafte Besteuerung für ausgeschüttete Gewinne ist wichtig ",
  "Die Besteuerung von Erbfällen bei größerem Gesellschafterkreis mit verschiedenen Interessen muss begünstigungsfähig sein",
  "Einzelne Gesellschafter sollen die Gesellschaft einfach verlassen können",
  "Die Möglichkeit, Gesellschaftsanteile zu veräußern oder zu vererben, soll eingeschränkt werden",
  "Die Abfindung für ausscheidende Gesellschafter soll weitestmöglich begrenzt werden",
  "Die Gesellschaft soll kapitalmarktfähig sein",
  "Externe Fremdkapitalaufnahme soll leicht möglich sein",
  "Unternehmerische Mitbestimmung durch Arbeitnehmer soll beschränkt oder vermieden werden",
  "Es wichtig, dass die wirtschaftlichen Angelegenheiten der Gesellschaft vertraulich bleiben",
  "Die Rechtsform der Gesellschaft steht für hohe Reputation und (internationale) Bekanntheit",
  "Eine Zersplitterung der Anteile in der Generationenfolge (Erbgang) soll verhindert werden",
]
export const choices = ["Trifft voll zu", "Trifft groBtenteils zu", "Trifft teilweise zu", "Trifft wenig zu", "Trifft uberhaupt nicht zu"];
